/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-01-11 08:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/min2/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/min2/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668994634552L));
    _jspx_dependants.put("jar:file:/D:/min2/pro07/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 1. 회원가입후 공지사항 글 열람, 비회원은 볼 수 없음 -->\r\n");
      out.write("<!-- 2. 관리자로 로그인하여 .. -->\r\n");
      out.write("<!-- 3. 일반회원은 자유게시판, qna게시판에 글을 작성하고 삭제할 수 있다. -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- bootstrap CDN -->\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("  	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- 하단 로고 슬라이더 CDN -->\r\n");
      out.write("  	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js\"></script>\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	<!-- template style -->\r\n");
      out.write("    <style>\r\n");
      out.write("    /* Add a gray background color and some padding to the footer */\r\n");
      out.write("    footer {\r\n");
      out.write("      background-color: #f2f2f2;\r\n");
      out.write("      padding: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .carousel-inner img {\r\n");
      out.write("      width: 100%; /* Set width to 100% */\r\n");
      out.write("      min-height: 200px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Hide the carousel text when the screen is less than 600 pixels wide */\r\n");
      out.write("    @media (max-width: 600px) {\r\n");
      out.write("      .carousel-caption {\r\n");
      out.write("        display: none; \r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  	</style>	\r\n");
      out.write("  	<!-- template style -->\r\n");
      out.write("  	\r\n");
      out.write("  	<!-- header -->\r\n");
      out.write("  	<style>\r\n");
      out.write("  	.logo-img { width: 180px; height: 27px;}\r\n");
      out.write("  	.navbar-inverse { background-color: #fff; border-color: #fff; }\r\n");
      out.write("  	.navbar-inverse .navbar-nav>li>a:focus, .navbar-inverse .navbar-nav>li>a:hover { color: #222; }\r\n");
      out.write("  	.navbar-inverse .navbar-nav>li>a { color: #222; }\r\n");
      out.write("  	.nav>li>a:focus, .nav>li>a:hover { color: #222; }\r\n");
      out.write("  	.navbar-inverse .navbar-nav>li>a { color: #222; }\r\n");
      out.write("  	</style>\r\n");
      out.write("  	\r\n");
      out.write("  	<!-- 메인 슬라이더 이미지 크기 조절 -->\r\n");
      out.write("  	<style>\r\n");
      out.write("  	.carousel-inner>.item>a>img, .carousel-inner>.item>img, .img-responsive, .thumbnail a>img, .thumbnail>img { height: 312px; }\r\n");
      out.write("  	</style>\r\n");
      out.write("  	\r\n");
      out.write("	<!-- 하단 로고 슬라이더 -->\r\n");
      out.write("	<style>\r\n");
      out.write("	h2{\r\n");
      out.write("	  text-align:center;\r\n");
      out.write("	  padding: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	/* Slider */\r\n");
      out.write("	\r\n");
      out.write("	.slick-slide {\r\n");
      out.write("	    margin: 0px 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.slick-slide img {\r\n");
      out.write("	    width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.slick-slider\r\n");
      out.write("	{\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    box-sizing: border-box;\r\n");
      out.write("	    -webkit-user-select: none;\r\n");
      out.write("	    -moz-user-select: none;\r\n");
      out.write("	    -ms-user-select: none;\r\n");
      out.write("	            user-select: none;\r\n");
      out.write("	    -webkit-touch-callout: none;\r\n");
      out.write("	    -khtml-user-select: none;\r\n");
      out.write("	    -ms-touch-action: pan-y;\r\n");
      out.write("	        touch-action: pan-y;\r\n");
      out.write("	    -webkit-tap-highlight-color: transparent;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.slick-list\r\n");
      out.write("	{\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    overflow: hidden;\r\n");
      out.write("	    margin: 0;\r\n");
      out.write("	    padding: 0;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-list:focus\r\n");
      out.write("	{\r\n");
      out.write("	    outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-list.dragging\r\n");
      out.write("	{\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	    cursor: hand;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.slick-slider .slick-track,\r\n");
      out.write("	.slick-slider .slick-list\r\n");
      out.write("	{\r\n");
      out.write("	    -webkit-transform: translate3d(0, 0, 0);\r\n");
      out.write("	       -moz-transform: translate3d(0, 0, 0);\r\n");
      out.write("	        -ms-transform: translate3d(0, 0, 0);\r\n");
      out.write("	         -o-transform: translate3d(0, 0, 0);\r\n");
      out.write("	            transform: translate3d(0, 0, 0);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.slick-track\r\n");
      out.write("	{\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    top: 0;\r\n");
      out.write("	    left: 0;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-track:before,\r\n");
      out.write("	.slick-track:after\r\n");
      out.write("	{\r\n");
      out.write("	    display: table;\r\n");
      out.write("	    content: '';\r\n");
      out.write("	}\r\n");
      out.write("	.slick-track:after\r\n");
      out.write("	{\r\n");
      out.write("	    clear: both;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-loading .slick-track\r\n");
      out.write("	{\r\n");
      out.write("	    visibility: hidden;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.slick-slide\r\n");
      out.write("	{\r\n");
      out.write("	    display: none;\r\n");
      out.write("	    float: left;\r\n");
      out.write("	    height: 100%;\r\n");
      out.write("	    min-height: 1px;\r\n");
      out.write("	}\r\n");
      out.write("	[dir='rtl'] .slick-slide\r\n");
      out.write("	{\r\n");
      out.write("	    float: right;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-slide img\r\n");
      out.write("	{\r\n");
      out.write("	    display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-slide.slick-loading img\r\n");
      out.write("	{\r\n");
      out.write("	    display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-slide.dragging img\r\n");
      out.write("	{\r\n");
      out.write("	    pointer-events: none;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-initialized .slick-slide\r\n");
      out.write("	{\r\n");
      out.write("	    display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-loading .slick-slide\r\n");
      out.write("	{\r\n");
      out.write("	    visibility: hidden;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-vertical .slick-slide\r\n");
      out.write("	{\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    height: auto;\r\n");
      out.write("	    border: 1px solid transparent;\r\n");
      out.write("	}\r\n");
      out.write("	.slick-arrow.slick-hidden {\r\n");
      out.write("	    display: none;\r\n");
      out.write("	}	\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("	<style>\r\n");
      out.write("	.footer-logo { width: 200px; height: 40px; }\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<header>\r\n");
      out.write("	<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("	  <div class=\"container-fluid\">\r\n");
      out.write("	    <div class=\"navbar-header\">\r\n");
      out.write("	      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("	        <span class=\"icon-bar\"></span>\r\n");
      out.write("	        <span class=\"icon-bar\"></span>\r\n");
      out.write("	        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("	      </button>\r\n");
      out.write("	      <a class=\"navbar-brand\" href=\"/\"><img class=\"logo-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/logo.png\" alt=\"로고\"></a>\r\n");
      out.write("	    </div>\r\n");
      out.write("		<!-- 주소 -->\r\n");
      out.write("	    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("	      <ul class=\"nav navbar-nav\">\r\n");
      out.write("	        <li class=\"dropdown\">\r\n");
      out.write("        		<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">민주평통소개\r\n");
      out.write("        		<span class=\"caret\"></span></a>\r\n");
      out.write("        		<ul class=\"dropdown-menu\">\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/page1\">설치근거 및 연혁</a></li><!-- 연혁 -->\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/page2\">사무처</a></li><!-- 사무처장 소개 -->\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/page3\">찾아오시는길</a></li><!-- 지도 -->\r\n");
      out.write("        		</ul>\r\n");
      out.write("      		</li>\r\n");
      out.write("	        <li class=\"dropdown\">\r\n");
      out.write("        		<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">뉴스·공지\r\n");
      out.write("        		<span class=\"caret\"></span></a>\r\n");
      out.write("        		<ul class=\"dropdown-menu\">\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/new\">새소식</a></li><!-- 게시판 -->\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list\">공지사항</a></li><!-- 게시판 -->\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/coverage\">보도자료</a></li><!-- 게시판 -->\r\n");
      out.write("        		</ul>\r\n");
      out.write("      		</li>\r\n");
      out.write("	        <li class=\"dropdown\">\r\n");
      out.write("        		<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">국민참여\r\n");
      out.write("        		<span class=\"caret\"></span></a>\r\n");
      out.write("        		<ul class=\"dropdown-menu\">\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list\">평화통일정책제안</a></li><!-- 게시판 or 자유게시판 -->\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/qna/list\">민원신청</a></li><!-- QnA -->\r\n");
      out.write("          			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/free/list\">자유게시판</a></li><!-- 자유게시판 -->\r\n");
      out.write("        		</ul>\r\n");
      out.write("      		</li>      		\r\n");
      out.write("	      </ul>\r\n");
      out.write("	      <!-- 회원 비회원 구분 + 관리자 구분 -->\r\n");
      out.write("	      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("        	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("	      </ul>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-sm-8\">\r\n");
      out.write("    <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("      <!-- Indicators -->\r\n");
      out.write("      <ol class=\"carousel-indicators\">\r\n");
      out.write("        <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("        <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      </ol>\r\n");
      out.write("\r\n");
      out.write("      <!-- Wrapper for slides -->\r\n");
      out.write("      <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("        <div class=\"item active\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/slider1.jpg\" alt=\"메인슬라이더1\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/slider2.jpg\" alt=\"메인슬라이더2\"> \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- slider 좌, 우 컨트롤 버튼 -->\r\n");
      out.write("      <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("        <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"sr-only\">Previous</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("        <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"sr-only\">Next</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-sm-4\">\r\n");
      out.write("    <div class=\"well\">\r\n");
      out.write("      <p>새소식<br><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/detail.do?bid=2\">·2022 정부포상 수여식 개최</a>\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"well\">\r\n");
      out.write("       <p>공지사항<br><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/detail.do?bid=1\">·사무처 공무직 근로자(비서) 채용 공고\r\n");
      out.write("</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"well\">\r\n");
      out.write("       <p>보도자료<br><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/free/detail.do?fid=1\">·고위공무원 전보(2022.12.26.자)\r\n");
      out.write("</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container text-center\">    \r\n");
      out.write("  <br>\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/banner1.jpg\" class=\"img-responsive\" style=\"width:100%\" alt=\"배너1\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\"> \r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/banner2.jpg\" class=\"img-responsive\" style=\"width:100%\" alt=\"배너2\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/banner3.jpg\" class=\"img-responsive\" style=\"width:100%\" alt=\"배너3\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <hr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("   <section class=\"customer-logos slider\">\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\" alt=\"하단로고1\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("      <div class=\"slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main/logo1.gif\"></div>\r\n");
      out.write("   </section>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $('.customer-logos').slick({\r\n");
      out.write("        slidesToShow: 6,\r\n");
      out.write("        slidesToScroll: 1,\r\n");
      out.write("        autoplay: true,\r\n");
      out.write("        autoplaySpeed: 1500,\r\n");
      out.write("        arrows: false,\r\n");
      out.write("        dots: false,\r\n");
      out.write("        pauseOnHover: false,\r\n");
      out.write("        responsive: [{\r\n");
      out.write("            breakpoint: 768,\r\n");
      out.write("            settings: {\r\n");
      out.write("                slidesToShow: 4\r\n");
      out.write("            }\r\n");
      out.write("        }, {\r\n");
      out.write("            breakpoint: 520,\r\n");
      out.write("            settings: {\r\n");
      out.write("                slidesToShow: 3\r\n");
      out.write("            }\r\n");
      out.write("        }]\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"container-fluid text-left\">\r\n");
      out.write("	<p class=\"footer_logo\"><img class=\"footer-logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/footer_logo.png\" alt=\"하단로고\"/></p>\r\n");
      out.write("	<p class=\"address\">04605 서울특별시 중구 장충단로 84 민주평화통일자문회의사무처 ㅣ 전화번호 (주간) 02-2250-2300 / (야간) 02-2250-2280<br/>Copyright© THE PEACEFUL UNIFICATION ADVISORY COUNCIL. All Rights Reserved.</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/index.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/index.jsp(7,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(239,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	        	<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginForm\"><span class=\"glyphicon glyphicon-log-in\"></span> 로그인</a></li>\r\n");
          out.write("          		<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/agree\">회원가입</a></li>\r\n");
          out.write("        	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/index.jsp(243,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("          		<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout\">로그아웃</a></li>\r\n");
          out.write("          		<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/read\">회원정보</a></li>\r\n");
          out.write("        	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/index.jsp(247,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sid eq \"admin\"}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          		<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/main\">관리자 페이지</a></li>\r\n");
          out.write("          		<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/list\">회원목록</a></li>\r\n");
          out.write("        	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
